### ISSUE TITLE
Ccminer 2.2.3 constantly downloads every "run"

### ISSUE THREAD

**Issue by platinum4** [UselessGuru/MultiPoolMiner#10]
It's because you're putting two of the same miner into the same folder, it will want to overwrite itself each run; split these into -x86 and -x64 directories instead of smashing them into 1 directory

**Comment by UselessGuru** [comment]
Fixed. 

https://github.com/UselessGuru/MultiPoolMiner/commit/623db9e91ae67f5289bb9aa9d14f447f36ad3c40

If Ok please close - thanks!
