### ISSUE TITLE
Cryptonight rework - When Update

### ISSUE THREAD

**Issue by evanvz** [UselessGuru/MultiPoolMiner#100]
Hi @UselessGuru 

I assume you're working on the fix.

Thanks
E

**Comment by UselessGuru** [comment]
Maybe later... I am working on three versions same time.

**Comment by evanvz** [comment]
Hi

I think like maybe a lot of people using your build we appreciate it, your time that is.

I do understand and can see that your doing a lot on the main build, but are concern that we may be forgotten.

Saying that, thank you for all your work and we can't wait for then next update with all the mayor changes been made over at the main build.

E
