### ISSUE TITLE
Negative accuracy causes algo to jump on top of the profitability list.

### ISSUE THREAD

**Issue by mkirov0** [UselessGuru/MultiPoolMiner#15]
I just noticed an algo (x11evo in my case) to jump on top of the profitability list while having -200% accuracy. I think the negative sign makes MPM to multiply current profit -= ( - 200% * Current Profit ).  I fixed it by deleting the x11evo stats, but posting here FYI in case its a simple fix. Its also possible it hasn't happened to anyone else, because I tend to keep my stats across updates, so they are pretty old now.
UG feel free to close the issue once you read it.

**Comment by UselessGuru** [comment]
>  just noticed an algo (x11evo in my case) to jump on top of the profitability list while having -200% 

I saw that too. This is why introduced a new tuning parameter '-MinAccuracy' in MPM 3.4.1.
https://github.com/UselessGuru/MultiPoolMiner/releases/tag/3.4.1
