### ISSUE TITLE
Only first GPU hash rate and power usage is recorded for NBMiner

### ISSUE THREAD

**Issue by mkirov0** [UselessGuru/MultiPoolMiner#16]
I noticed NBMiner when bechmarking Cuckaroo29 is recording only the first GPU hash rate and power usage in the respective stats files. I have only 1 GPU on my test PC so maybe that's why it didn't make any difference there. I can upload logs if needed, but not much to see there IMHO. 
Also I noticed X16RT and X16RTVeil show on the list of algos, but I don't see any difference between them. This is just something I noticed and FYI. I dont use all available pools, so it may be needed for some other pool, but from what I was able to gather there is no difference between them.

**Comment by mkirov0** [comment]
On ClaymoreEthash_v14.7 seeing a message "Missed option value after -di value". My guess is its a typo, but I couldn't find it... 😞 If that helps, I tried copying the new claymore14.7.ps1 to the older MPM 3.4.0 version where I have claymore14.6(working perfectly), but still no luck.

Please also let me know if you would like me to create separate issues for these. I'm thinking they are small and quick fixes and thats the reason I'm adding them up to the same open issue.

EDIT:
Now getting similar issue with Gminer "--devices argument missing" which points to the same same code. So maybe its not that simple and ironically enough the issues may be connected after all. 😄

**Comment by UselessGuru** [comment]
> Also I noticed X16RT and X16RTVeil show on the list of algos, but I don't see any difference between them. This is just something I noticed and FY

There are 3 variants:
X16RTGin
X16RTVeil 
X16RT is generic; some miners can do Gin & Veil

**Comment by UselessGuru** [comment]
> "Missed option value after -di value"
> Now getting similar issue with Gminer "--devices argument missing" 

Thank you for reporting. Please give more information. 
I need 
- the exact command line of that miner
- a dump of your devices (http://localhost:399/devices)

**Comment by UselessGuru** [comment]
> I noticed NBMiner when bechmarking Cuckaroo29 is recording only the first GPU hash rate and power usage in the respective stats files

Problem found and fixed in 3.4.4:
https://github.com/UselessGuru/MultiPoolMiner/releases/tag/3.4.4

I cannot understand the issue with Claymore or Gminer. Please clarify.

**Comment by mkirov0** [comment]
Yesterday after numerous system restarts and even moving the Claymore14.7.ps1 to MPM 3.4.0 where I have a working Claymore14.6 it kept giving me the same error while at the same time 14.6 was working. Today I go back to 3.4.2 to get the localhost:3999/devices dump - it works like there was no problem. Only explanation I can arrive to (as outrageous as it sounds) is that someone from Microsoft is trolling me. 
Anyway all of the issues are resolved now. Still waiting for Gminer to benchmark, but my bet is on the problem with it being gone, since I was able to isolate the same piece of code as in claymore which is working now.
Thanks for clarifying the X16Rt variations.
Thanks for fixing the problem with NBminer. For me its one of the best for Cuckaroo29.
