### ISSUE TITLE
Version 3.4.5 is released

### ISSUE THREAD

**Issue by UselessGuru** [UselessGuru/MultiPoolMiner#18]
Download link:
https://github.com/UselessGuru/MultiPoolMiner/archive/3.4.5.zip

Please also report if all is working fine - only so I can know that we get rid of all the bugs.

#### Core changes
- Added config parameter '-DisableEstimateCorrection'; reduce the algo price by a correction factor (actual_last24h / estimate_last24h) to counter pool overestimated prices
- Changed funtion Get-EquihasPers to Get-AlgoCoinPers & EquihashPers.txt to AlgoCoinPers.txt
- List pool names being queried for pricing information
- Use only configured devices when API becomes available
- Workround when module 'ThreadJob' cannot be loaded: use normal 'Start-Job'

#### Miner changes
- Added AMD-SgminerFancyIX_v0.6.0.0; support for Allium, Argon2Ddyn, Lyra2v3, Lyra2z, Lyra2zz, MTP, Phi2, X22i & X25x
- Added NVIDIA-CcminerBMW512; support for BMW512
- Fixed AMD-SgminerFancyIX_v0.6.0.0; algorithm Argon2d was broken
- Fixed AMD_NVIDIA-PhoenixminerEthash_v4.2c, does not work with AMD driver versions 2841.5, 2841.19 or 2906.8
- Fixed AMD-TeamRed_v0.5.5; enabled detection of failed GPUs
- Fixed NVIDIA-CcminerMTP_v1.1.23; requires CUDA 10.1.00 or higher
- Fixed WarmupTime for Sgminer*; allow up to 90 seconds to build binaries
- Updated AMD_CPU_NVIDIA-NanoMiner_v1.5.2; support for Cuckarood29 and RandomHash (CPU only), added Ethash binaries for AMD Radeon RX 5700 and AMD Radeon RX 5700 XT cards
- Updated AMD_NVIDIA-BMiner_v15.7.2; support for Cuckarood29
- Updated AMD_NVIDIA-Gminer_v1.52; support for Cuckarood29
- Updated AMD_NVIDIA-lolMiner_v0.85; removed 'Equihash' from its name 'cause it does non Equihash algos as well
- Updated AMD-SRBMinerCryptonight_v1.9.1
- Updated AMD-WildRig_v0.18.0; suppport for GltGlobalHash
- Updated CPU-Jayddee_v3.9.6.1; crash mining Hodl with aes-sse42
- Updated NVIDIA-CcminerKlausT_v8.25
- Updated NVIDIA-CcminerZenemy_v2.1
- Updated NVIDIA-NBMiner_v23.3; support for Cuckarood29
- Updated NVIDIA-TTMiner_v2.2.6; support for Cuckarood29

#### Pool changes
- Fixed BlockMasters; did not return any objects
- Implement workaround for Zpool(Coins) anti-DDoS protect (pool allows only 6 API calls per minute)
- Nicehash: Use API v2 (new Nicehash)
- Support for new config parameter '-DisableEstimateCorrection'

#### Balances changes
- Implement workaround for Zpool(Coins) anti-DDoS protect (pool allows only 6 API calls per minute)
- Nicehash: Request API v1 (old Nicehash) & v2 (Nicehash)

**Comment by m-bosch** [comment]
Thanks again for the update, installing and benchmarking the new miners as we speak.

To bad to hear you cant continue here. internal issues in the team?

For the nicehash, is it better to set the new btc address according to new nicehash or better to keep the old address (that i cant see in new nicehash).

IMHO you should use the new address.

**Comment by UselessGuru** [comment]
> To bad to hear you cant continue here. internal issues in the team?

Aaronsace has been quiet for months, and when today when I tried to create the release I noticed that I could not commit anymore. 

> For the nicehash, is it better to set the new btc address according to new nicehash or better to keep the old address (that i cant see in new nicehash).

Don't know myself. I can successfully mine to my old address, and I can see the balance on new nicehash. So I still don't know if a new address is a necessity or not.

**Comment by m-bosch** [comment]
Thanks for the response.

> Don't know myself. I can successfully mine to my old address, and I can see the balance on new nicehash. So I still don't know if a new address is a necessity or not.

Looks like the old address is merged to the new one because i can see it on the new nicehash under my new address?

Aaronsace responded on the origin repo btw

**Comment by UselessGuru** [comment]
> i can see it on the new nicehash under my new address

I can see the balance of both - my internal and external - BTC address in the GUI, but new NH say miner not found when I enter my od NH internal address.
So I guess I should switch to the new internal address.

**Comment by m-bosch** [comment]
> > i can see it on the new nicehash under my new address
> 
> I can see the balance of both - my internal and external - BTC address in the GUI, but new NH say miner not found when I enter my od NH internal address.
> So I guess I should switch to the new internal address.

Sounds logical indeed, i will switch also.

Maybe a stupid question but when i change things i config. do i need to restart all or does the next loop read the new config?

**Comment by UselessGuru** [comment]
> does the next loop read the new config?

It does. All settings in config.txt are dynamic. So there is no need to restart.

**Comment by mkirov0** [comment]
I noticed CcminerKlausT_v8.25 benchmarking X17 it gives me about 80% lower hashrate than Zenemy and T-rex. Idk if its just me, but if this is the result for everyone, I'm not sure its worth keeping it enabled. The more important find is the miner does not recognize yescrypt as a valid algo. I am not sure this is MPM issue since I tried starting it outside MPM and it still does not recognize yescrypt although it clearly has it listed in the miner readme file. Just posting this FYI.

**Comment by UselessGuru** [comment]
> I noticed CcminerKlausT_v8.25 benchmarking X17 it gives me about 80% lower hashrate than Zenemy and T-rex. Idk if its just me, but if this is the result for everyone, I

Thank you!

In the next version the following algos will be disabled (more to come):

X17: NVIDIA-CcminerKlausT_v8.25, NVIDIA-CcminerSp_v1.5.81 & NVIDIA-CcminerSuprMiner_v2.0.7 (fastest free miner NVIDIA-CcminerAlexis_v1.5)
C11: NVIDIA-CcminerNevermore_v0.5 &  NVIDIA-CcminerSuprMiner_v2.0.7 (fastest free miner 
NVIDIA-CcminerAlexis_v1.5)
Equihash1445: AMD_NVIDIA-BMiner_v15.7.2 & AMD_NVIDIA-lolMiner_v0.8.5 (fastest miner are NVIDIA-MiniZEquihash_v1.4o & AMD_NVIDIA-Gminer_v1.52)
HMQ1725: NVIDIA-CcminerTrex_v0.12.1 (fastest miner NVIDIA-CryptoDredge_v0.20.2)


Feel free to initiate pull requests. Preferrably you comment the slow algo in the miner file like this:
[#"x17"        = "" #X17, NVIDIA-CcminerAlexis_v1.5 is faster](url)

**Comment by mkirov0** [comment]
Gminer_v1.52 did not download the binary at all. I attempted to move the .ps1 to my old 100% working MPM 3.4.4 and still have the same result. It did not register the new miner file at all.

Something else I noticed (I don't think its exclusive to 3.4.5) is that x16rt fluctuates a lot and the 10% threshold tolerance for stats updating does not catch it every time. I am not sure if its possible to change the threshold for just one algo, but changing it to 15% on x16rt would help update the stats on each loop and not have to wait for 3 times to force update it.

**Comment by UselessGuru** [comment]
>  (I don't think its exclusive to 3.4.5) is that x16rt fluctuates a lot
> I am not sure if its possible to change the threshold for just one algo, but changing it to 15%

This is a general issues with most X... algorithms. They are just a combination of existing algos being executed in certain orders. They will always have a higher fluctuation.
The only workaround is an extended benchmark time (like X16r already has).
And no, there is no way for an algo specific margin.

So far no one has come up with THE perfect solution for these algos :-(

**Edit: In the next release the X16rt algo will have an extended benchmark interval of 3.**

**Comment by mtbor** [comment]
Nicehash is a no-go for me at the moment.  The new addresses do not resolve.  I've updated the internal wallet address to the new platform which made no difference.

**Comment by mtbor** [comment]
Also, I'm unsure as to the usage of the -DisableEstimateCorrection flag...  Is estimate correction enabled by default?   Would:    "DisableEstimateCorrection": true     added in the config.txt file turn this functionality off?

**Comment by UselessGuru** [comment]
> Is estimate correction enabled by default?

Yes.

> Would: "DisableEstimateCorrection": true added in the config.txt file turn this functionality off?

Exactly.

or by adding ' -DisableEstimateCorrection' to the start batch file

For all parameters you can always check the parameter format by looking at the running config (http://localhost:3999/runningconfig.html)

**Comment by UselessGuru** [comment]
> Nicehash is a no-go for me at the moment. The new addresses do not resolve. do not resolve. 

Please explain. NH (v1 & v2) is working fine here.

**Comment by mkirov0** [comment]
I mine Nicehash with external address and the change hasn't affected me at all.

**Comment by mtbor** [comment]
I believe the stratum address  for nicehash in the US is as "USA" instead of "US".

**Comment by mtbor** [comment]
Compare:
[2019-07-25 14:38:32] : Fast-connecting to cryptonightr.us-new.nicehash.com:3375 pool ...
[2019-07-25 14:38:32] : SOCKET ERROR - [cryptonightr.us-new.nicehash.com:3375] CONNECT error: GetAddrInfo: No such host is known. 


[2019-07-25 14:40:11] : Fast-connecting to cryptonightr.usa-new.nicehash.com:3375 pool ...
[2019-07-25 14:40:11] : Pool cryptonightr.usa-new.nicehash.com:3375 connected. Logging in...

**Comment by mtbor** [comment]
I have done a quick work around using a static region + pool line in the nicehash pool file.  I'm guessing the real fix is way easier...

**Comment by mtbor** [comment]
A couple of other things I noticed which I'm unsure of...   Formatting in algorithms.txt for Equihash variants is sort of random...   Formatting like this:  '"equihashr15050":  "EquihashR15050",'  doesn't seem to work properly.  The algorithms that are formatted as '"equihash144":  "Equihash1445",' seem to be working.

Additionally, when I tried to make a quick change in the config.txt file to put my region to "eu" for testing, the change did not take.  I verified the updated config was running at "http://localhost:3999/runningconfig.html", but the log files show everything still headed to a US stratum.

**Comment by smarcello** [comment]
I can notice multiple lines of :
INFO: Pinging monitoring server. Your miner status key is: xxx. 
INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
after the following API's have failed:
Zpool, BlazePool.
Hope it helps.

**Comment by UselessGuru** [comment]
> Additionally, when I tried to make a quick change in the config.txt file to put my region to "eu" for testing, 

The correct value would be 'Europe'. Then the setting is applied properly on the next run.

**Comment by UselessGuru** [comment]
> Compare:
[2019-07-25 14:38:32] : Fast-connecting to cryptonightr.us-new.nicehash.com:3375 pool ...
[2019-07-25 14:38:32] : SOCKET ERROR - [cryptonightr.us-new.nicehash.com:3375] CONNECT error: GetAddrInfo: No such host is known.

Uups. That slipped my attention. Use this:

[NiceHash.zip](https://github.com/UselessGuru/MultiPoolMiner/files/3439248/NiceHash.zip)

> I'm guessing the real fix is way easier...

The fix IS much easier....  The fixed pool file will be in the next release (3.4.7)

**Comment by mtbor** [comment]
Thank you for all of your hard work, it's amazing that you take the time to make user suggestions a part of multipoolminer going forward.

Especially estimate correction, makes a lot of difference.

**Comment by mkirov0** [comment]
Can confirm the new miner files UG uploaded as a solution to mtbor's issue resolve the issue I had with Gminer listed above.

**Comment by UselessGuru** [comment]
Offical releases are available here: https://github.com/MultiPoolMiner/MultiPoolMiner/releases
