### ISSUE TITLE
On 3.4.5 new line

### ISSUE THREAD

**Issue by smarcello** [UselessGuru/MultiPoolMiner#19]
new info line, why is it happening?

2019-07-21 20:32:54 INFO: All benchmarking miners have failed, start new loop immediately. 

Thanks !

**Comment by UselessGuru** [comment]
> 2019-07-21 20:32:54 INFO: All benchmarking miners have failed, start new loop immediately.

As the line says:
All benchmarking miners failed (for whatever reason). So MPM will start a new loop immediately.

**Comment by carlo0000** [comment]
zpool still not good

WARNING: Pool API (Zpool) has failed.

**Comment by UselessGuru** [comment]
> zpool still not good

There is not much we can do. Zpool has a limit of 6 API calls per minute (one every 10 seconds). If you have Zpool, ZPoolCoins & Zpool querying in parallel the error occurs.

Possible workaround: Only keep Zpool, and remove the ZpoolCoin miner and Zpool balances file.

To change this will require substantial changes to the pool files.

**Comment by carlo0000** [comment]
ok so not need of zpool balance to work
i will try,
it s better to have  older data from pool then no pool, so if app check even one avery 10 minute  or even 30 still good, because i guess if more miner running on same ip it get worse

**Comment by UselessGuru** [comment]
> ok so not need of zpool balance to work

Try these files - they should improve the situation a bit (but the pool will still fail occasionally)

[Zpool.zip](https://github.com/UselessGuru/MultiPoolMiner/files/3424270/Zpool.zip)

If they work better ll add them to the next release

**Comment by carlo0000** [comment]
or should i switch to an other pool?
AHashPool looks similar

i tested the file on 2 miners but pool was there on 1 computer for a minute or 2 then was gone again
i think it update to often
i remove from 1 computer and keep zpool  on 1 computer, sometimes it fail but looks better for now
i add it back to the 2nd computer later to see it it will fail more often

**Comment by smarcello** [comment]
Sorry, same old story repeats randomly:
2019-07-24 12:18:01 INFO: Mining for you. Donation run will start in 19 hour(s) 44 minute(s). 
2019-07-24 12:18:02 INFO: Loading pool information (BlockMasters; MiningPoolHub; NiceHash; NLPool; Ravenminer; ZergPool; Zpool) - this may take a minute or two. 
2019-07-24 12:18:57 INFO: Pinging monitoring server. Your miner status key is: xxxxxx. 
2019-07-24 12:18:58 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
than same lines each 1 minute till:
2019-07-24 18:06:49 INFO: Pinging monitoring server. Your miner status key is: 1H4xhbgThzeQLyjtz1LifgW9Bkojgjdyy5. 
2019-07-24 18:06:54 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
2019-07-24 18:07:57 INFO: Pinging monitoring server. Your miner status key is: xxxxxx. 
2019-07-24 18:07:59 INFO: Miner Status (https://multipoolminer.io/monitor/miner.php): Success
2019-07-24 18:14:22 INFO: Starting MultiPoolMiner® v3.4.5 © 2017-2019 MultiPoolMiner.io
2019-07-24 18:14:47 INFO: Web dashboard and API (version 0.95) running on http://localhost:3999. 
Of course at 18:14:22 a restart was needed.
It repeats with all last versions, including the latest.
During pinging of multipoolminer.io no mining occurs.

**Comment by mkirov0** [comment]
@smarcello I think I've seen that before. Can you upload the logs or if you have the info from localhost:3999/runningminers at the time of the issue. The config file will also help. You should edit any personal info you have on it.
I think I have an idea, but the info will help a lot.

**Comment by smarcello** [comment]
Sure, thanks:
[runningminers.zip](https://github.com/UselessGuru/MultiPoolMiner/files/3427962/runningminers.zip)
[MultiPoolMiner_2019-07-24_18-33-00.zip](https://github.com/UselessGuru/MultiPoolMiner/files/3427976/MultiPoolMiner_2019-07-24_18-33-00.zip)

**Comment by smarcello** [comment]
sorry, here is my config:
[Config.txt.zip](https://github.com/UselessGuru/MultiPoolMiner/files/3428020/Config.txt.zip)

**Comment by mkirov0** [comment]
In your config file I saw an extra comma after `"CPU-TpruvotCorei7_v1.3.1": {}` 
under the `"Miners": {` 
section. If that's not a typo resulting from the personal info editing it should be corrected in your config.

Can you try and run AMD-ClaymoreNeoscrypt_v1.2 **outside** MPM, with the arguments listed on line 7 ("Arguments": ) of your runningminers file uploaded earlier and see if it will run ok?

**Comment by UselessGuru** [comment]
> i tested the file on 2 miners but pool was there on 1 computer for a minute or 2 then was gone again
i think it update to often

There will be changes to the pool file in the coming version. Stay tuned.

**Comment by smarcello** [comment]
@mkirov0 Thanks. 
AMD-ClaymoreNeoscrypt_v1.2 runs OK outside MPM.
