### ISSUE TITLE
EthminerEthash

### ISSUE THREAD

**Issue by mkirov0** [UselessGuru/MultiPoolMiner#2]
@UselessGuru 
You probably already know this, but the AMD-NVIDIA miners under the MinerLegacy section in the config file show and work as they are supposed to.
I am seeing an issue with EthminerEthash_v17.1. Windows does not recognize the `%2e`. It causes it to fail on benchmark after 3 unsuccessful attempts.
Ethminer devs recommend adding another `%`. They talk about it here [https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md](https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md) and they have a section talking specifically about windows.
I attempted adding another `%` to the MPM Ethminer file, but what I am seeing is it concatenates the `e` from `%2e` to my password. For example if my user is "user" and my pass is "password" it passes  to the miner - "user **e**password". I did test the `%%2e` outside MPM and it worked.

**Comment by UselessGuru** [comment]
I don't quite understand. Can you provide me sample files?
What is your username & what do you have in the password field. And with witch pool?

**Comment by mkirov0** [comment]
I can't believe this, but now when I reverted the `%%2e` to `%2e` (in Ethminer.ps1) in order to provide you with samples it connected to the pool (miningpoolhub) and started mining with no issues for now. If anything comes up I'll reopen the issue.
