### ISSUE TITLE
Benchmarking issues

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#2]
Two of my miners have been benchmarking for the last 8 hours and there seem to be some issues :)

One of the miners (4x1070) which was only benching mph algo's got 'stuck' a couple of times where it just kept on benchmarking one miner/algo combination. Woke up today to see it had been at it for 6+ hours.

Other miner (1x1080) had been restarting a certain miner for 400+ times when I was asleep.

I now realise this could very well be due to to me changing parameters in config.ps1, for example '$Watchdog = $true', which might conflict with your new crash detection?

edit: after setting '$Watchdog = $false' again, I still see it benching a miner/algo for too long. It's been running for 10+ minutes now and don't think it will continue to the next by itself.

![image](https://user-images.githubusercontent.com/7703320/34467916-c2e9d3d6-eefd-11e7-89a2-b380a5cb8ce2.png)

**Comment by hapklaar** [comment]
The $delay variable in config.ps1 does not seem to be honored. I have it set to 8, but during benchmarking I regularly saw the next miner being started when the previous one was still running/quitting. This resulted in warings in the new miner: API bind to port 4068 failed - using port 4069

**Comment by UselessGuru** [comment]
>  The $delay variable in config.ps1 does not seem to be honored

That code is still there. ???

Did it create a valid benchmark file for the miner in question?
I've notices that some miner's API ist very unreliable, e.g CcminerAlexis78hsr.

**Comment by hapklaar** [comment]
Euh yes code is still there :) Shouldn't it be? I've attached a large log.
[2018-01-01_05-56-10.zip](https://github.com/UselessGuru/MultiPoolMiner/files/1596244/2018-01-01_05-56-10.zip)

**Comment by UselessGuru** [comment]
Changed the way dynamic ports were allocated. Please try the latest build.

**Comment by hapklaar** [comment]
Latest build has many errors for me, preventing it from starting correctly. Please see #13 item 3 (was this closed by accident?)

**Comment by hapklaar** [comment]
Looks like this issue is fixed. Benchmarking now completes without issue, although I disabled bminer and ccmineralexis before I started. There is a new issue for which I'll create a new post.
