### ISSUE TITLE
Can I copy my existing Stat folder to this to save time benchmarking? and an Index error.

### ISSUE THREAD

**Issue by paulpoco** [UselessGuru/MultiPoolMiner#20]
Exception setting "Index": "The property 'Index' cannot be found on this object. Verify that the property exists and can be set."
At C:\Users\pjb\Desktop\MultiPoolMiner-master\MultiPoolMiner.ps1:235 char:9
+         $Miner.Index = [String]$Miner.Index
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting

https://pastebin.com/XReASGwt
https://pastebin.com/sdxZkDPa

**Comment by platinum4** [comment]
Stats folder may work yes across different masters; i've reset for most recent tho

**Comment by UselessGuru** [comment]
> At C:\Users\pjb\Desktop\MultiPoolMiner-master\MultiPoolMiner.ps1:235 char:9

Working on it... will update a new version soon

**Comment by UselessGuru** [comment]
Should be fixed now. Please download the zip file and copy the contents over the old installation.

**Comment by UselessGuru** [comment]
Fixed in latest builds
