### ISSUE TITLE
Cannot find an overload for "GetData" and the argument count: "2" when getting stats from BMiner

### ISSUE THREAD

**Issue by luismcv** [UselessGuru/MultiPoolMiner#22]
Cannot find an overload for "GetData" and the argument count: "2".
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest
    + PSComputerName        : localhost

2018-01-04 01:18:41 ERROR: Failed to connect to miner (BMiner_GeforceGTX1080Ti).

**Comment by luismcv** [comment]
Solved by removing the third parameter of GetData() in APIs/BMiner.ps1:

class BMiner : Miner {
[PSCustomObject]GetData ([String[]]$Algorithm, [Bool]$Safe = $false, [String]$DebugPreference = "SilentlyContinue") {

**Comment by UselessGuru** [comment]
Thanks! Changed: https://github.com/UselessGuru/MultiPoolMiner/commit/421404d31b159a56b8b6ebe0eb4bccc70fb6cd20
