### ISSUE TITLE
Power GPU remains 'Pending'

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#26]
Doing benchmarking  again and see Power GPU not being updated. Is this expected?

![image](https://user-images.githubusercontent.com/7703320/34591057-089fecac-f1bb-11e7-8dc1-d9f10f34e89e.png)

**Comment by UselessGuru** [comment]
[Fixed](https://github.com/UselessGuru/MultiPoolMiner/commit/4aab09832d93219286252f75faacbedd20ee038d)
