### ISSUE TITLE
Upon first and fresh start, getting log dir access error

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#27]
![image](https://user-images.githubusercontent.com/7703320/34591339-e9d18130-f1bc-11e7-8546-98d0422b3238.png)

Only happens on first start.

I suspect Logs directory needs to be created sooner in script

**Comment by UselessGuru** [comment]
[Fixed](https://github.com/UselessGuru/MultiPoolMiner/commit/054a0ef43bfa5a8719d3829e369d0b9515e8ffbf)
