### ISSUE TITLE
follow up on issue 26 (GPU powerdraw = Pending)

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#29]
Because you closed #26 and I cannot reopen, creating new issue:

Does not seem fixed, looks same as before

![image](https://user-images.githubusercontent.com/7703320/34607029-00dec3b0-f212-11e7-8702-7ae50aa90c95.png)

**Comment by UselessGuru** [comment]
Cause found, will update soon.

Thanks for your patience btw.

**Comment by UselessGuru** [comment]
Try the latest version (download zip file).

Please Close Issue if OK.

**Comment by Coinminer24** [comment]
I appear to be having the same issue, when benching the power draw appears but not in the calculation table

**Comment by UselessGuru** [comment]
https://github.com/UselessGuru/MultiPoolMiner/archive/master.zip

**Comment by hapklaar** [comment]
Sweet.
![image](https://user-images.githubusercontent.com/7703320/34630609-1ba75fee-f26d-11e7-8e5c-a0cb1dce91a2.png)
