### ISSUE TITLE
Logs dir access error not fixed 

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#30]
#27 is still not fixed, cannot reopen so new issue!

![image](https://user-images.githubusercontent.com/7703320/34619703-50ec0bca-f243-11e7-88ca-ae12ba0c2e04.png)

**Comment by UselessGuru** [comment]
Now it is really fixed

**Comment by hapklaar** [comment]
Yes, confirmed! :)
