### ISSUE TITLE
Fresh start, benchmarking does not proceed

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#31]
![image](https://user-images.githubusercontent.com/7703320/34621243-a6be0ab2-f248-11e7-8518-96a4aaec8395.png)

(do you test your own code? :))

**Comment by UselessGuru** [comment]
Would dare to try again?

https://github.com/UselessGuru/MultiPoolMiner/archive/master.zip

**Comment by hapklaar** [comment]
Seems fixed, I'll test some more and close if fixed!
