### ISSUE TITLE
Newly added miner (992d60f) wrong cmdline

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#32]
This miner does not support '--submit-stale' and quits.

 PS. this miner is submitting invalid shares, just like the other one from djm34, so you might want you not add it at all. tpruvot's version is slightly slower, but no invalid shares at all.

**Comment by UselessGuru** [comment]
> This miner does not support '--submit-stale' and quits.

[Fixed](https://github.com/UselessGuru/MultiPoolMiner/commit/519bb5ed38abeb1a4e8cd4b5da8eed221dcca534) - a copy-paste error.
