### ISSUE TITLE
cudart64_91.dll not found (Klaust)

### ISSUE THREAD

**Issue by Coinminer24** [UselessGuru/MultiPoolMiner#33]
When the miner tries to run Klaust I get the error "cudart64_91.dll not found" it appears I don't have the correct CUDA version; however, I have latest Nvidia drivers and both cards are Maxwell. Any idea why this would be?

**Comment by UselessGuru** [comment]
> When the miner tries to run Klaust I get the error "cudart64_91.dll not found"

Does Bin\NVIDIA-KlausT818_CUDA91\cudart64_91.dll exist?

If not then try to extract it from the binary package in Downloads\

**Comment by Coinminer24** [comment]
Ah, realize what happened - the virus scanner blocked the extraction so only the miner extracted (before being quarantined)

**Comment by Coinminer24** [comment]
So... seem to be getting the issue even after adding the DLL files back in. Any ideas?

**Comment by UselessGuru** [comment]
> the virus scanner blocked the extraction 

Exclude the MPM folder from the virus scanner, then delete the Bin folder and start over. MPM will re-fetch all binaries.

**Comment by Coinminer24** [comment]
> Exclude the MPM folder from the virus scanner, then delete the Bin folder and start over. MPM will re-fetch all binaries.

Will need to switch AV, current only allows me to mark individual files as excluded. Will try and figure out why manually placing it there isn't working. Thank you for all of the help. It's really cool to see the power draw now.

**Comment by platinum4** [comment]
Yee, re-close this issue if it's fixed.

**Comment by UselessGuru** [comment]
Thanks for your feedback!
