### ISSUE TITLE
743:Write-Log -Message "Waiting for 30 seconds to start next run" <# UselessGuru #>

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#34]
This should probably reflect '$Interval' from config.ps1, as it takes exactly that amount of seconds.

**Comment by UselessGuru** [comment]
```
    for ($i = $Strikes; $i -gt 0 -or $Timer -lt $StatEnd; $i--) {
        if ($Downloader) {$Downloader | Receive-Job}
        Start-Sleep 10
```
$Strikes is 3 -> max 3 * 10 secs.

**Comment by hapklaar** [comment]
hmm, I mean this specific INFO message is not reflecting the $interval set in config.ps1, which is correctly used for timing the cycles.

![image](https://user-images.githubusercontent.com/7703320/34633093-0a257212-f27a-11e7-80cb-45326f9781b3.png)

**Comment by UselessGuru** [comment]
Fixed. Download latest ZIP
