### ISSUE TITLE
No issue!

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#35]
Just wanted to say you're doing a great job UselessGuru. Many issues solved today and it purring along just peachy at the moment on my 6GPU rig!

Keep up the good work ;)

![image](https://user-images.githubusercontent.com/7703320/34632408-83c05f56-f275-11e7-8255-faa2a7d620ce.png)

**Comment by UselessGuru** [comment]
Great to hear - thanks for your support!
