### ISSUE TITLE
Doesn't use zpool for equihash or Lyra2RE2

### ISSUE THREAD

**Issue by Coinminer24** [UselessGuru/MultiPoolMiner#38]
For some reason the miner will not use Zpool for these two algos, despite them being supported. It goes to MPH. I am just using Zpool and MPH. It also happens if only Zpool is specified.

**Comment by Coinminer24** [comment]
Been doing more testing, it appears it's only really Lyra2RE2 that it won't mine on Zpool. If I remove miningpoolhub then equihash will go to zpool. My goal is to primarily mine Zpool with MPH as failover, but this means I can't use Lyra2RE2.

**Comment by Coinminer24** [comment]
Any ideas why this may be happening? Do I need to edit to ensure it recognises that zpool can accept Lyra?

**Comment by hapklaar** [comment]
Seeing same issue here with latest code. I have equihash and lyra2re2 enabled in config.ps1, together with pools MPH and ZH, but they are never tried on NH.

![image](https://user-images.githubusercontent.com/7703320/34888006-c9144b6e-f7c8-11e7-9f87-3a96506d288b.png)

**Comment by Coinminer24** [comment]
I haven’t had a chance to retest but the above is exactly the issue I am having. You can also see in that screenshot that lyra2re2 is not showing in zpool

**Comment by evanvz** [comment]
On zpool Lyra2RE2 = Lyra2v2 You'll have to add Lyra2v2 to your algos to mine in your config file. Not sure what the effect will be on other pools. I've also removed all other pool files except zpool pool files.
