### ISSUE TITLE
PowerShell 5.0 not installed

### ISSUE THREAD

**Issue by evanvz** [UselessGuru/MultiPoolMiner#39]
Good day Master @UselessGuru 

You poeple are just great. I found MPM after NH hack and I think what you people have done is the next best thing after BTC. Many thanks.

No, I've been toying with the main MPM and it works just great, untill II saw your personal project. Currenlty running your main 2.7.1.2 on dual 1050Ti and 1060 6GB. Its just ticks along nicelay.

Saying that, I tried your personal master version with all the new setups with power readings and profit and so on, but when I start the "Setup.bat" it tells me that powershell 5.0 is not installed.

I've copied the files over to my Desktop without success.

Please assist.

Great thanks.
E

**Comment by hapklaar** [comment]
Try installing WMF5

https://www.microsoft.com/en-us/download/details.aspx?id=50395

or WMF5.1

https://www.microsoft.com/en-us/download/details.aspx?id=54616

**Comment by evanvz** [comment]
Hi @hapklaar 

Thanks for the advise. Haven't had change to check, as I've been having other idiot problems on my side.

Cheers.
