### ISSUE TITLE
MPM trying to start two miners

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#4]
Seeing MPM trying to start BMiner, which immediately crashes. MPM starts DSTM, which runs fine but then tries to start BMiner again while running DSTM. This fails again, then DSTM gets restarted > loop >
bad juju

BMiner is 1st in benchmarking list for equihash. Apparently did not crash during benchmarking
DSTM is second.

![image](https://user-images.githubusercontent.com/7703320/34468061-e9b323a2-ef00-11e7-9880-984ce08b75f6.png)

**Comment by UselessGuru** [comment]
> Apparently did not crash during benchmarking

The miner is launched the same way, regardless of benchmark mode or not.

I've built in 2 methods to troubleshoot this kind of issues:
 - In the log file (the new log file 2018-...) you should find the exact parameter that was used to start the miner. Open a cmd window and execute that command.
- In the \Bin\[MinerName] folder you will fing a cmd file for each run miner. Execute this cmd to troubleshoot.

**Comment by hapklaar** [comment]
When I run BMiner_Equihash_MiningPoolHub.cmd manually, it runs fine now. It has the same cdmline as the one from the log where it crashes.

It's not so bad the miner crashes, this happens sometimes. However shouldn't mpm exclude it from being tried after 3 failures? It now seems to loop indefinitely. 

I've added a log showing this happening, maybe you can spot what's going wrong.
[2018-01-01_14-30-02.txt](https://github.com/UselessGuru/MultiPoolMiner/files/1596239/2018-01-01_14-30-02.txt)

**Comment by UselessGuru** [comment]
>It's not so bad the miner crashes, this happens sometimes. However shouldn't mpm exclude it from being tried after 3 failures? It now seems to loop indefinitely.

This is part of the WatchDog code which I have not really tried to understand.

Are you overclocking? Especially memory?

**Comment by hapklaar** [comment]
I have no overclock active at the moment, all stock.

**Comment by platinum4** [comment]
You have a mixed-card rig probably so try `$DeviceSubTypes = $false` in `Config.ps1`

**Comment by hapklaar** [comment]
No mixed card rig, a single 1080 in this one.

**Comment by platinum4** [comment]
I never got Bminer to work I've just deleted the `Bminer.ps1` in `\Miners`

**Comment by UselessGuru** [comment]
Should be fixed now. Please download the zip file and copy the contents over the old installation.

**Comment by hapklaar** [comment]
Haven't seen this happening anymore, so close
