### ISSUE TITLE
How to check why miner failing?

### ISSUE THREAD

**Issue by Coinminer24** [UselessGuru/MultiPoolMiner#40]
My X17 miners (whether alexis or Klaus) stop being used and drop out of the miner list after a while, I am wondering if it is due to variability in the algo accuracy. Is there a way I can check why they are moving off the list of miners?

**Comment by UselessGuru** [comment]
There might be an issue with the watchdog. I have not yet quite undestood how that works in detail.

Can you turn it off?

**Comment by Coinminer24** [comment]
Seems to be OK when the watchdog is off. Unfortunately I’m also having another issue - zpool not up properly at the moment, but even with watchdog on, it’s not switched to MPH at all

**Comment by UselessGuru** [comment]
Watchdog and switching are basically not related. 

Watchdog disables miners & pools if they fail consistently and will remove them from the internal list of miners / pools. This might trigger a switch.

Switching is usually triggered by 3 reasons:
- Better combo of miner&pool detected (accuracy & price)
- New unbenched miner became available (pool opened a new algo) or a new miner file was created
- miner or pool got removed (watchdog)

**Comment by Coinminer24** [comment]
Apologies I used the wrong word - i meant switch as in “failover”. I had set zpool in pool list, other pools explicitly excluded except MPH. Zpool was down for maintenance but script just kept retrying zpool instead of trying MPH. The pool was down but API was up so api calls were still answered. Does the watchdog rely primarily on API presence? Otherwise unsure why it wouldn’t have moved to MPH

**Comment by UselessGuru** [comment]
Watchdog relies on web request API for pools and on reported hash rates for miners as read from miner API
