### ISSUE TITLE
CcminerSp doesn't need the wrapper

### ISSUE THREAD

**Issue by luismcv** [UselessGuru/MultiPoolMiner#42]
It works fine with Ccminer's API:

            API          = "Ccminer"
            Wrap         = $false

**Comment by rtom098** [comment]
Hey, I tried this:
set Wrap = false in CcminerSp.ps1

Still benchmarking without stopping.
Was it correct or did i choose wrong file to edit?

**Comment by luismcv** [comment]
You have to change lines 72 and 74 from:

            API          = "Wrapper"
            Port         = $Port
            Wrap = $true

to 

            API          = "Ccminer"
            Port         = $Port
            Wrap = $false

**Comment by UselessGuru** [comment]
@luismcv 
> Yes, that's the right file, but you have to change lines 72 and 74 from:

Thank you - I did not notice that it had an API. [Changed Ccminer to use API instead](https://github.com/UselessGuru/MultiPoolMiner/commit/278e8f3e31e18c46c90c54f1bd2d43072a6576cc).
