### ISSUE TITLE
Benchmarking ccminer.exe skein takes hours

### ISSUE THREAD

**Issue by rtom098** [UselessGuru/MultiPoolMiner#43]
Hey there! Nice project so far - but I'm having problems with the benchmark. While benchmarking I needed to kick out FireiceNvidia.ps1, PalginNvidia_HSR.ps1 and PalginNvidia_Neoscrypt.ps1 because they throw error messages. 

**All others are correctly benchmarked so far, except these:** 
- CcminerSp (Skein)
- Ccminer-2.2.3-x64 (Equihash)

**Issue:**
So actually I'm stuck more than 1,5hours at the CcminerSp (Skein). It takes forever... The ccminer.exe window looks fine, he is hashing with 974168 KH/s. 

Any idea how to solve this? 

----
PS - Info: I just have one card, GTX 1080ti.
Got it working by setting "$DeviceSubTypes = $True in Config.ps1"

PS2: A good info in installation process would be to exclude your miner directory from Windows defender. A lot of miners where throwing trojan warnigns by default. When I added the folder I saw that the standard multipoolminer directories where already inserted there (not by me).

**Comment by luismcv** [comment]
> I needed to kick out FireiceNvidia.ps1, PalginNvidia_HSR.ps1 and PalginNvidia_Neoscrypt.ps1 

I had to disable those miners too.

> So actually I'm stuck more than 1,5hours at the CcminerSp (Skein). It takes forever...

The wrapper isn't working, but it's not needed. Have a look at the issue I reported for how to fix it: https://github.com/UselessGuru/MultiPoolMiner/issues/42

> Ccminer-2.2.3-x64 (Equihash)

I don't had any issues with that algo, but I had with cryptonight. To disable an algo that's causing problems with a miner without disabling the whole miner, just add _ at the beginning: 

    "_neoscrypt"     = "" # my best values for 1080ti/1070/10603G " -i 26" # beaten by Ccminer-Palgin-Nist5

**Comment by UselessGuru** [comment]
> PalginNvidia_HSR.ps1 and PalginNvidia_Neoscrypt.ps1

They do not offe an proper API so the wrapper  it trying to gather the has hrate from the screen output. Hower this may take wile (usually much longer than one loop).

As workaround you can create a hash rate file manually by copying and editing an existing one.
I just include Palgin because the are really much faster.
Palgin has announced API support soon - until then we'll have to take what we get ;-)

> PS - Info: I just have one card, GTX 1080ti.
> Got it working by setting "$DeviceSubTypes = $True in Config.ps1"

No need for this with only one card. Behaves exactly the same.

> PS2: A good info in installation process would be to exclude your miner directory from Windows defender

Hardly possible. Most miners will trigger AV anyway. And I don't want to interfere with AV. Too many different products. But thanks for the idea and feedback!

**Comment by rtom098** [comment]
thanks for your help, trying the manual thing out now. maybe there is a way to just throw a screenshot into a folder or copy&paste the cmd-window data output to a file from which one you take the paramenters? :)

**Comment by UselessGuru** [comment]
> CcminerSp (Skein)

CcminerSP was configured to use Wrapper instead of API. [I've uploaded a corrected miner file](https://github.com/UselessGuru/MultiPoolMiner/commit/278e8f3e31e18c46c90c54f1bd2d43072a6576cc).

**Comment by platinum4** [comment]
I think this is fixed ho
