### ISSUE TITLE
neoscrypt not tried on MPH

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#44]
After adding neoscrypt to my algo list in config.ps1, it only tries this algo on NH. Should this algo be tried on MPH, when I have 
$PoolName = @('MiningPoolHub') and 
$Algorithm = @("lyra2z","equihash","ethash","neoscrypt") configured?

neoscrypt is mineable @ MPH

**Comment by hapklaar** [comment]
could be same issue as #38

**Comment by UselessGuru** [comment]
MPH was broken, fixed in
https://github.com/UselessGuru/MultiPoolMiner/commit/e8a8373ba56dae55cf05c4f01896e09d3742518a

Please close if OK
