### ISSUE TITLE
MPH not used anymore, only MPHC?

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#45]
I used to run with only one pool file, MiningPoolHub.ps1, but this is not working anymore, getting  WARNING: No pools available.

Only when MiningPoolHubCoins.ps1 is present, mining to MPH is working. Is this by design?

If so, what is the difference between the two?

**Comment by UselessGuru** [comment]
> mining to MPH is working. Is this by design?

I'll have to investigate. Stay tuned.

> If so, what is the difference between the two?

See readme, parameter $algorithm

**Comment by UselessGuru** [comment]
> I'll have to investigate. Stay tuned.

Problem found. Will update soon!

**Comment by UselessGuru** [comment]
Fixed with https://github.com/UselessGuru/MultiPoolMiner/commit/e8a8373ba56dae55cf05c4f01896e09d3742518a

Please close if OK.
