### ISSUE TITLE
Missing prerequisite?

### ISSUE THREAD

**Issue by Jaerin** [UselessGuru/MultiPoolMiner#47]
I cloned the git repository.  Ran the setup.bat and configured the config.ps1.  Then I'm trying to execute start.bat.  Normal MPM is working fine.

I'm attempting to run your fork of MPM and it seems to be failing with the following:

```
**********************
Windows PowerShell transcript start
Start time: 20180108145820
Username: MACHINENAME\Username
RunAs User: MACHINENAME\Username
Configuration Name: 
Machine: MACHINENAME (Microsoft Windows NT 10.0.16299.0)
Host Application: powershell -version 5.1 -noexit -executionpolicy bypass -windowstyle maximized -command & .\multipoolminer.ps1
Process ID: 18008
PSVersion: 5.1.16299.98
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.98
BuildVersion: 10.0.16299.98
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is .\Logs\2018-01-08_14-58-20.txt
2018-01-08 14:58:20 INFO: Loading miner APIs...
2018-01-08 14:58:20 INFO: Updating exchange rates from Coinbase...
2018-01-08 14:58:20 INFO: Loading saved statistics...
2018-01-08 14:58:22 INFO: Loading pool information...
2018-01-08 14:58:27 INFO: Selecting best pool for each algorithm...
2018-01-08 14:58:27 INFO: Getting miner information...
PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'DifferenceObject' because it is null."
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\CoinMiners\MultipoolMiner-Useless\MultiPoolMiner.ps1:193 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : 
ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
Compare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.
At D:\CoinMiners\MultipoolMiner-Useless\MultiPoolMiner.ps1:193 char:71
+ ... e-Object {$Type.Count -eq 0 -or (Compare-Object $Type $_.Type -Includ ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
```

When I tried to debug the script it appeared like the GPU devices were not being populated correctly.  I tried to manually run the get-GPUDevices cmdlet, but it would not run unless I specifically ran Powershell 6.0.  From what I saw the Type value was not getting populated from the Miners.

I could be missing a prerequisite or something, but don't believe so.

**Comment by hapklaar** [comment]
Knows issue #25 , do you have 1 GPU?

**Comment by Jaerin** [comment]
Does look to be the same issue.  I have a single 1080Ti in this machine I'm testing on.

**Comment by Jaerin** [comment]
Should line 149 of Include.psm1 be incrementing $Devices instead of $Device_ID?  It looks like when I debug that $Devices += $Device_ID ends up being 0 += 1, but $Devices is not 1 when the if ($Devices) { line on 152 comes around.

**Comment by Jaerin** [comment]
Looks like this logic is broken.  So if Subtypes is set to $False like it is by default you end up with no Miners.

https://github.com/UselessGuru/MultiPoolMiner/blob/master/Include.psm1#L146

Setting Subtypes to True allows the script to continue forward.  So it looks like there is needs to be a fix to how the Device_ID is incremented when Subtypes is set to false.

**Comment by Jaerin** [comment]
So with Subtypes = True I still notice that at the top of the output it is still saying there are 0 GPUs

   Device: GeForce GTX 1080 Ti [GPU Devices: 0]

**Comment by UselessGuru** [comment]
> Device: GeForce GTX 1080 Ti [GPU Devices: 0]

This means device with ID '0'. Ill change this output.

> Knows issue #25 , do you have 1 GPU?

Thanks for the hint, can not really test. Will investigate.

**Comment by Jaerin** [comment]
I think the problem is though that because Device_ID starts at 0 Devices always will be 0 and therefore the If (Devices) statement in the next clause will never get run.   Devices += Device_ID will always be 0 if Device_ID starts at 0.

**Comment by UselessGuru** [comment]
@Jaerin 

> Should line 149 of Include.psm1 be incrementing $Devices instead of $Device_ID? It looks like when I debug that $Devices += $Device_ID ends up being 0 += 1, but $Devices is not 1 when the if ($Devices) { line on 152 comes around.

Can you remove the offensive line 149? Error still there?

**Comment by Jaerin** [comment]
The error still happens because ultimately it doesn't populate the GPU variable correctly.  I believe you need to change the code to increment Devices to 1 or change the logic on the next if to look at something other than Devices because the way it is written Devices is getting set to 0.  The code above seems to be embedding Devices inside a $GPU object.   I'm not sure if that should be done here or what.   I'm not 100% sure what the Subtypes variable is intended to do.

**Comment by UselessGuru** [comment]
@Jaerin 

- Can you please download the latest zip (contains extra code to create debug data)
- unpack into a new directory
- copy config.ps1 from original
- create a folder 'Debug' in the MPM folder
- start MPM briefly until it starts looking for miners
- stop MPM
- zip and upload files in Debug folder

Thanks

**Comment by Jaerin** [comment]
Here you go

**Comment by Jaerin** [comment]
So is Devices on line 148 of Include.psm1 supposed to be a count of devices or what is that value supposed to be?  Right now it looks like it is a summation of all device_ID's.  The problem is if there is only 1 device that value is 0 since the first Device_ID is always 0.  This means the If (Devices) would not get called and the Type doesn't get set.

**Comment by UselessGuru** [comment]
Does this help?
https://github.com/UselessGuru/MultiPoolMiner/commit/e86ca1e9a6685553a5231ffc6cd150342009e45a

I'll close this one because the same issues is dealt with here:
https://github.com/UselessGuru/MultiPoolMiner/issues/25
