### ISSUE TITLE
ClaymoreNvidia is shown 5 times in table

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#48]
![image](https://user-images.githubusercontent.com/7703320/34732101-874e21de-f564-11e7-9671-51d8ecf8e5a5.png)

**Comment by UselessGuru** [comment]
LOL...

Can please (with the latest build)
- Stop MPM
- create a Debug folder in the MPM directory
- let it run until you see the 5x miner
- stop and upload the files in the Debug folder
- remove Debug folder again.

**Comment by hapklaar** [comment]
Here you go

[Debug.zip](https://github.com/UselessGuru/MultiPoolMiner/files/1616521/Debug.zip)

**Comment by UselessGuru** [comment]
Problem fixed:

https://github.com/UselessGuru/MultiPoolMiner/commit/6bf0d3e2c31fb69092a943e18e264ebbe8c6c7c1

Please close if the fix works for you - thanks.

**Comment by platinum4** [comment]
I think this is fixed now.
