### ISSUE TITLE
Make Nicehash region configurable in Config.ps1

### ISSUE THREAD

**Issue by platinum4** [UselessGuru/MultiPoolMiner#52]
Kinda pointless I guess to specify 'US' in Config.ps1 and have Nicehash auto-default to EU since it is in the \Pools file.  Make this a $Nicehash_Region variable in Config.ps1 and also add a $Nicehash_Wallet in Config.ps1 so people can put an internal address there.

Also a flag for $Is_Internal_Wallet = $true/$false so that you can have a fee of 2% for internal and 3-5% for external instead of manually hard-coding this.

**Comment by UselessGuru** [comment]
> Also a flag for $Is_Internal_Wallet = $true/$false so that you can have a fee of 2% for internal and 3-5% for external instead of manually hard-coding this.

Good point!

**Comment by platinum4** [comment]
This was just a suggestion, not an issue that needed solving.
