### ISSUE TITLE
EWBF miner file missing

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#56]
API file is present, but no miner file in /Miners for it.

**Comment by UselessGuru** [comment]
Miner config uploaded:
https://github.com/UselessGuru/MultiPoolMiner/commit/c780046c095b05cd6e9d9c7471317204489ed6b3

**Comment by hapklaar** [comment]
Nope, don't see it!

**Comment by UselessGuru** [comment]
[See here](https://github.com/UselessGuru/MultiPoolMiner/commit/8cd047ac191ac8eba041410e938d3beefb2079a3). I've uploaded the file to the wrong directory.

**Comment by platinum4** [comment]
Miner never loads even if it's moved.

Sad!

**Comment by platinum4** [comment]
it's named `miner.exe` not `zminer.exe`

**Comment by platinum4** [comment]
Doesn't work on split card rigs either; only selects 1 GPU in the array

Weak!

**Comment by hapklaar** [comment]
works fine on mine, after changing zminer.exe to miner.exe (all GTX1070 though)
![image](https://user-images.githubusercontent.com/7703320/34905455-3148aece-f859-11e7-823f-464bbcccc306.png)

**Comment by UselessGuru** [comment]
Fixed the miner file. Change executable to miner.exe

**Comment by platinum4** [comment]
Dude what the shit this doesn't work on split card rigs at all it only selects 1 gpu out of the array of gpu devices
