### ISSUE TITLE
Enhancement: Add GPU power factor to config.ps1

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#57]
Looks like wattage measured is consistently 10% too low. Would be nice if this could be adjusted by adding a configurable power factor (1.1 for me) to config.ps1

**Comment by UselessGuru** [comment]
> Looks like wattage measured is consistently 10% too low.

Wattage measured is 1:1 what NVIDIA-SMI reports.

Just increase poser cost by that factor and you get the same power cost ;-)

**Comment by platinum4** [comment]
@hapklaar yo close this man. This is resolved by adjusting your configuration accordingly in `Config.ps1`
