### ISSUE TITLE
Missing space in CommonCommands

### ISSUE THREAD

**Issue by luismcv** [UselessGuru/MultiPoolMiner#6]
The issue is present in Ccminer-2.2.3-x64.ps1 and Ccminer-2.2.3.ps1

Should be:

$CommonCommands = " --submit-stale"

or else the miner fails launching.

Or, probably better, separate $Port$Command$CommonCommands in Arguments for all miners:

Arguments = "-a $_ -o $($Pools.$Algorithm.Protocol)://$($Pools.$Algorithm.Host):$($Pools.$Algorithm.Port) -u $($Pools.$Algorithm.User) -p $($Pools.$Algorithm.Pass) -b $Port $Command $CommonCommands"

**Comment by UselessGuru** [comment]
Fixed in https://github.com/UselessGuru/MultiPoolMiner/commit/9189b96d3d01bafcee1bddb1cf68ddd487ae5ed2

> Or, probably better, separate $Port$Command$CommonCommands in Arguments for all miners:
Good point! Ill do that!
