### ISSUE TITLE
BMiner crashes on launch, but if you run the .cmd file; it will run OK

### ISSUE THREAD

**Issue by platinum4** [UselessGuru/MultiPoolMiner#60]
Hi,

Every time UG_MPM tries to load BMiner it immediately "crashes" according to MPM and doesn't mine.  If you run the generated .cmd (without -polling) it will mine.

**Comment by UselessGuru** [comment]
Ccan you try the [updated Bminer 5.0.0](https://github.com/UselessGuru/MultiPoolMiner/commit/75e5907fb936c18724b4c8c3cfb663d3798595c4)? Thanks!

**Comment by platinum4** [comment]
New code
```
2018-01-15 05:43:32 INFO: Waiting to start next run
2018-01-15 05:43:32 ERROR: NVIDIA Miner 'BMiner' (Equihash) [GPU Devices: All] crashed: 'BMiner.exe -api 127.0.0.1:4041 -uri stratum://platinum4.z97g7.x@us-east.equihash-hub.miningpoolhub.com:17023 -nofee'
```

**Comment by hapklaar** [comment]
bminer is very shady software. Be sure to read up on people's experience with this miner

**Comment by platinum4** [comment]
bminer is very shady software. Be sure to read up on people's experience with this miner
