### ISSUE TITLE
Gigabyte GTX 1050 Ti GPU Power reading

### ISSUE THREAD

**Issue by evanvz** [UselessGuru/MultiPoolMiner#62]
Good day

@UselessGuru 

I'm currently using your master build and noticed that when I run the benckmark on my 1050, it doesn't seem to read the GPU power.

Please assists.

Thank you

**Comment by UselessGuru** [comment]
> GPU power

I cannot test this myself as I don't have a 1050.

For the power / cpu readout MPM requires "$Env:SystemDrive\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe" to be present.

Where is nvidia-smi.exe in your system?

**Comment by evanvz** [comment]
@UselessGuru 

Thanks for the comeback. I understand.

I'm running Nvidia 388.71 drivers. the nvidia-smi file is present and located as above. I also have a MSI 1060 6GB that benchmarks without problems.

Not really a problem for me at this time.

Great program... Many thanks for your work.

**Comment by evanvz** [comment]
@UselessGuru 

Is there perhaps anything I could provide you with, and out or something. I know this build is for your interest.

Appreciate.

Thanks again.

**Comment by evanvz** [comment]
Just as a note.

The 1050Ti doesn't support power readings. Not supported.

Max power is 75W.

So I just add it to my GPU PowerDraw.
