### ISSUE TITLE
NiceHash not being tried

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#63]
I have 3 pool files in /Pools, but NiceHash seems to be ignored

![image](https://user-images.githubusercontent.com/7703320/34962428-dbfabfd8-fa43-11e7-93a3-730da5984097.png)

**Comment by UselessGuru** [comment]
Why should it be listed? In your case there are faster pools for all of the chosen algorithms. MPM will only list the fastest pool per algo.

Just to prove my theory: Rename the other pools and NH will show.

**Comment by platinum4** [comment]
How did you get all that info are you on 21:9

Mine doesn't truncate it has so much less info than yours

**Comment by hapklaar** [comment]
I don't think so, it should list all pool/algo combinations that were enabled in config.ps1.

I changed the font size to be able to fit it on one screen.

**Comment by hapklaar** [comment]
#38 is probably same and would be by design if you're right on this.

**Comment by Coinminer24** [comment]
The difference on 38 is it happens even if the pool is not specified. So if you name zpool only, exclude other pools except MPH, it still doesn’t show zpool Lyra. My understanding was it should default to the specified pools unless the coin is not supported or down, in which case it would try the non specified pools. It will never try the excluded pools. Maybe I am wrong.

**Comment by UselessGuru** [comment]
> I don't think so, it should list all pool/algo combinations that were enabled in config.ps1.

MPM will only list one miner per algo

> PS what do you mean by 'fastest pool'.

I meant paying the highest price.

NH will only appear if it will offer you the best price for an algo.

**Comment by platinum4** [comment]
NH won't appear if you leave the fee at 3% for external wallets; it's the highest of all fees on top of the miner fees.
