### ISSUE TITLE
Conflicting paths in Ccminer-2.2.3-x64.ps1 and Ccminer-2.2.3.ps1

### ISSUE THREAD

**Issue by luismcv** [UselessGuru/MultiPoolMiner#7]
which is preventing one or the other to download. I solved it chaging the x64 path to

$Path = ".\Bin\NVIDIA-ccminer-2.2.3-x64\ccminer-x64.exe"

**Comment by UselessGuru** [comment]
Thanks - just fixed it!
https://github.com/UselessGuru/MultiPoolMiner/commit/623db9e91ae67f5289bb9aa9d14f447f36ad3c40
