### ISSUE TITLE
UselessGuru doesn't Merge Pull Requests

### ISSUE THREAD

**Issue by platinum4** [UselessGuru/MultiPoolMiner#70]
Come on bro.
https://github.com/UselessGuru/MultiPoolMiner/pull/69
Come onnnnnnnnnnnnnn

**Comment by UselessGuru** [comment]
Please redo your pull request, I've updated some miners.

**Comment by platinum4** [comment]
https://github.com/UselessGuru/MultiPoolMiner/pull/71
