### ISSUE TITLE
BMiner and Eminer crash at launch

### ISSUE THREAD

**Issue by jrafaelmdo** [UselessGuru/MultiPoolMiner#72]
Hi,

Every time UG_MPM tries to load BMiner or Eminer it immediately "crashes" according to MPM and doesn't mine.

This is issue doesnt happen with standard MPM, however I prefer your version better for the added information (power draw, etc) and would like to get it to work.

Please help. Thank you.

**Comment by UselessGuru** [comment]
This happens for some user (BGminer has the same problem in 'standard' MPM.

What is the value of '$UseAlternateMinerLauncher'? Try '$false'. This might help.

**Comment by jrafaelmdo** [comment]
Thank you for responding,

I applied the recommended setting and same behavior.

Anymore ideas ?

Thanks.

**Comment by UselessGuru** [comment]
> Anymore ideas ?

remove the two miners. :-(
