### ISSUE TITLE
Will not stop crashing miner

### ISSUE THREAD

**Issue by robl45** [UselessGuru/MultiPoolMiner#73]
Found the right place to post this.  this version will not kill a crashing miner at least during benchmarking.  As suggested in the other post, I did make hashrate and power files for the algo with 0 for hashrate and that got it moving, then it failed for next algo and I did it again.  Is there anyway to just kill the miner for a certain gpu?

**Comment by robl45** [comment]
On my other card Excavator is starting on nist5 and not doing anything with the gpu and just hanging, it benched pascal fine.  Its like watchdog is not working.

**Comment by UselessGuru** [comment]
@robl45 

There are some issues with the current implementation when it comes to nonstop loops. I'll change that somewhen.

As workaround create a hashrate file with 0 hash rate (copy an existing *hashrate.txt, rename it and edit it so that all hash rates will be 0.)

**Comment by robl45** [comment]
i've been doing that.  did it with the ones that crashed and ones that sat there.

**Comment by robl45** [comment]
This is really cool so far, but this isn't really a workaround.  I'm still benchmarking this thing constantly stopping and editing hashrate files.  You might want to put on the site a warning that the crash prevention is not working.

**Comment by UselessGuru** [comment]
I fixed watchdog.
