### ISSUE TITLE
$DeviceSubTypes = $True and selecting single devices

### ISSUE THREAD

**Issue by YoBii** [UselessGuru/MultiPoolMiner#74]
Hey guys. Unfortunately I'm not very familiar with powershell, so I'm having trouble coming up with something on my own. 

When using $DeviceSubTypes = $True where in the logic could one change the code to e.g. mine only with the second device? I tried some things and was able to change the DeviceSubType routine in Include.psm1 and make it so only one device shows up in overview but then MPM started launching miners on all devices again like with $DeviceSubTypes = $False. 

I know this feature is supposed to be implemented as a configurable option in the future but for know I'd be fine with just adding an if-statement somewhere. 

Thanks

PS: I know I could change each miner file, but I'd prefer it this way.

**Comment by UselessGuru** [comment]
> mine only with the second device?

What exactly do you mean by' the second device'?
If you mean you do not want to use the primary GPU for mining then this is not supported out of the box - not in this build nor in the official MultiPoolMiner.

**Comment by YoBii** [comment]
Yes, that's what I mean. I know it's not a feature in any MPM build atm and i'm not asking for implementation of it. 
Maybe you can just give me some hint to make some dirty/messy change to the code where it's like: 
if($Device.name -contains 1070) {} else{StartMining()}
Where MPM basically just skips any launch of miner software when that would mine on a 1070 for example.

Is that possible?

**Comment by UselessGuru** [comment]
> Is that possible?

Edit MultiPoolMiner.ps1 and look for the following line:

```
    $Miners = $AllMiners | Where-Object {(Test-Path $_.Path) -and ((-not $_.PrerequisitePath) -or (Test-Path $_.PrerequisitePath))}
```

Change it to 

```
    $Miners = $AllMiners | Where-Object {$_.Device -notlike "*1070*" } | Where-Object {(Test-Path $_.Path) -and ((-not $_.PrerequisitePath) -or (Test-Path $_.PrerequisitePath))}
```

This will not mine on any device that contains 1070 in the device name

**Comment by YoBii** [comment]
Awesome! Thank you.
