### ISSUE TITLE
Only mining Hashrefinery

### ISSUE THREAD

**Issue by robl45** [UselessGuru/MultiPoolMiner#75]
As you can see from the image, it doesn't even list hashrefinery as one of the choices for the algorithm yet it just keeps doing the algorithms on hashrefinery.  Hashrefinery, ahashpool, mph, and zpool are selected pools.

![image](https://user-images.githubusercontent.com/34346751/35708311-744288ae-077b-11e8-8897-5183418b3193.png)

**Comment by UselessGuru** [comment]
Two reasons: 
- Hashrefinery is giving you the best price for all algos
- The other pools are broken somehow.

Try renaming Hashrefinery.ps1 to _Hasrefinery.ps1 and restart MPM. What happens?
BTW: logs are always helpful

**Comment by robl45** [comment]
I guess maybe better description is its heavily favoring Hashrefinery while the main MPM would almost exclusively use Ahashpool.  Also why is it using different pools than what is listed for pool next to the algorithm?    Is that not how it works on this version?

**Comment by UselessGuru** [comment]
> Is that not how it works on this version?

It is using the exact same algorithms. One possible reason why my edition is favoring other pools are fees which are ignored in 'vanilla' MPM.
MPM alway mines the algo with the highest accuracy and then earning.

**Comment by robl45** [comment]
I mean to ask, does it look at earnings after powercosts or cust straight earnings when picking?

**Comment by UselessGuru** [comment]
profit (earnings - less power)

**Comment by YoBii** [comment]
I'm having a similar "issue", where the best algo/pool combos in the list are displayed as Zpool, but MPM starts and keeps mining that algorithm on different pools e.g. nicehash or ahashpool.
Basically it always lists Zpool as the most profitable pool for the majority of miners but only very rarely actually mines on zpool...
Don't think this is expected behavior?

**Comment by robl45** [comment]
I think it works, I just think the display on the this version is not quite up to date with what the miners are picking as it does appear to pick other things then what is being displayed next to each algorithm.

**Comment by robl45** [comment]
Just to add, there is definitely something a little weird here, I had to disable hashrefinery and remove the pool file to get it to start using ahashpool.  the main branch almost always favored ahashpool which makes sense because it is 1 percent fee versus 1.25 on hashrefinery.  If I had hashrefinery, ahashpool, and zpool on the main branch, they would all get used in a 24 hour period.  This version almost exclusively uses hashrefinery.  Its like its not grabbing updated numbers or something.

**Comment by robl45** [comment]
To further followup, I removed hashrefinery and now have zergpool, mph, ahashpool, and zpool.  It has not touched Zpool in over 24 hours.  I know zpool has higher fees, but in the main branch it would have at least touched it once or twice in 24 plus hours.
