### ISSUE TITLE
ccminer-x11gost vs ccmineralexishsr on blake2s

### ISSUE THREAD

**Issue by robl45** [UselessGuru/MultiPoolMiner#76]
On my gtx950, these two miners are almost identical in hashrate which means I watch them switch between each other like very minute.  Is there a preferred one so I can edit the hashrate on one of them to stop the constant switching when it mines blake2s?

**Comment by UselessGuru** [comment]
edit the miner file or create a 0 hash rate file.

**Comment by robl45** [comment]
Yes, but which one is preferred, is there one that reports a more true hashrate?

**Comment by UselessGuru** [comment]
There is no true hashrate. MPM read the hash rate from the miner through the miner API. What ever the miner says MPM believes.

**Comment by platinum4** [comment]
Close this.
