### ISSUE TITLE
EWBF.ps1

### ISSUE THREAD

**Issue by evanvz** [UselessGuru/MultiPoolMiner#77]
Hi @UselessGuru 

Just tried your new master and found this.

2018-02-02 17:01:57 INFO: Getting miner information...
ForEach-Object : Cannot bind parameter 'RemainingScripts'. Cannot convert the "Sleep" value of type "System.String" to type "System.Management.Automation.ScriptBlock".
At D:\Downloads\MPM\UselessGuru\MultiPoolMiner-master\Miners\EWBF.ps1:47 char:12
+ $Devices | ForEach-Object {
+            ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ForEach-Object], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.ForEachObjectCommand

**Comment by UselessGuru** [comment]
Thanks - fixed in https://github.com/UselessGuru/MultiPoolMiner/commit/2984ce9bae3ae045400b601dc60ac539f16adae3

**Comment by evanvz** [comment]
Shot
