### ISSUE TITLE
Nicehash Internal Wallet

### ISSUE THREAD

**Issue by evanvz** [UselessGuru/MultiPoolMiner#78]
Hi @UselessGuru 

See post about Nicehash and there internal wallet been asked howto on MPM Main site.

Sorry, I'm not a programmer but if you may, have a look at these changes for possible NH internal wallet.

Trying to use a different wallet for when I mine on Nicehash.

Was thinking :

Config.ps1
Add:
$NHWallet = 'YOURNICEHASHINTERNALWALLETHERE'

But in the NiceHash.ps1 pool file if I change all $Wallet strings to $NHWallet it doesn't work.

Only got it working if I add a string
$Wallet = "YOURNICEHASHINTERNALWALLETHERE"

No worries if you give this one a pass.

**Comment by UselessGuru** [comment]
Why so complicated?

Edit the Nicehas.ps1 file, uncomment the following line and pot your own BTC address there
# $Wallet = "3JQt8RezoGeEmA5ziAKNvxk34cM9JWsMCo"

Note: This will change in a coming version.

**Comment by evanvz** [comment]
Hi @UselessGuru 

That's why your the 'man'

Was just thinking for a setup process for a user to add it during config setup.

Noted. Done. Thanks again for a great app.

E
