### ISSUE TITLE
ZergPool

### ISSUE THREAD

**Issue by evanvz** [UselessGuru/MultiPoolMiner#79]
Hi @UselessGuru 

Not sure if you're interesset.

Someone asked for it on main MHM.

Did some reverse enginering lol My none programming skills. 

Taken from @Sniffdog SniffdogMiner.

[Zergpool.zip](https://github.com/UselessGuru/MultiPoolMiner/files/1691648/Zergpool.zip)

If I've overstepped please let me know.

Later
E

**Comment by UselessGuru** [comment]
https://github.com/UselessGuru/MultiPoolMiner/commit/6a828ba21d9b2b791ba937dfd464ae3a67cc70c5
