### ISSUE TITLE
Keeps trying to mine a pool even if the pool is down.

### ISSUE THREAD

**Issue by robl45** [UselessGuru/MultiPoolMiner#80]
Last night zergpool went down for hours and I checked and it was trying to mine zergpool even though the miner just said trying to connect over and over again.

**Comment by UselessGuru** [comment]
Did you enable watchodog?

**Comment by robl45** [comment]
Yes, watchdog is enabled.  I also didn't see anything saying api has failed like I do with zpoolcoins saying api failed all the time.

**Comment by evanvz** [comment]
Hi @UselessGuru

Got the some sort of problem.

Received a WARNING: Pool API (XYZ) has failed, but miner started mining on said pool, and receiving "Connection failed" messages in miner screen.

Is there a timeout check that can be done or set somehow.

Watchdog set to true

Any assistance will be appreaciated.

Thank you
E

**Comment by UselessGuru** [comment]
> Received a WARNING: Pool API (XYZ) has failed,

Failing to contact the pool does NOT stop MPM mining on it. It will just continue with old data.

Wachdog works as this:
$watchdog Include this command to enable the watchdog feature which detects and handles miner and other related failures. It works on a unified interval that is defaulted to 60 seconds. Watchdog timers expire if three of those intervals pass without being kicked. There are three stages as to what action is taken when watchdog timers expire and is determined by the number of related expired timers.

Stage 1: when 1 timer expires relating to one miner/algorithm combination, the one miner/algorithm combination is kicked
Stage 2: when 2 timers expire relating to one miner file, the one miner file is kicked
Stage 3: when 3 timers expire relating to one pool, the pool is kicked

**Comment by evanvz** [comment]
Hi @UselessGuru 

Thanks for that. I wasn't sure how many time it ran between I noticed it. In the meantime I've removed that pool from my list. Sorted.

E
