### ISSUE TITLE
BlazePool

### ISSUE THREAD

**Issue by robl45** [UselessGuru/MultiPoolMiner#84]
[Blazepool.zip](https://github.com/UselessGuru/MultiPoolMiner/files/1711704/Blazepool.zip)

Currently mining on blazepool with this file if anyone wants to try.

**Comment by robl45** [comment]
It appears to be working from the wallet, but I notice that it doesn't seem to be putting the algorithm in front of mine.blazepool.com.  Maybe someone can take a look?

**Comment by UselessGuru** [comment]
Should be fixed:

https://github.com/UselessGuru/MultiPoolMiner/commit/13325430433f95e8d1657bb7f4ec9b833b64ca50

If this works then please close the issue - thank you!

**Comment by robl45** [comment]
This works, but please note, I edited the zergpool file which does not appear to have the host correct.
