### ISSUE TITLE
Renamed all Miners -> will re-benchmark everything

### ISSUE THREAD

**Issue by UselessGuru** [UselessGuru/MultiPoolMiner#85]
I have modified all miner files so they match the names of 'vanilla' MPM.
This change was needed so we can run 'vanilla' AND UG-Edition from the same directory.

Unfortunately this also means we have to re-benchmark everything again.
So if you are using the new miner files I recommend you clear you 'Stats' directory first. This will also help speed up your system :-)

**Comment by robl45** [comment]
Is there a need to update to this?  rebenchmarking is a problem for me as probably 20 files or more needed to be modified with zero hashrates due to this version not kililng the miner if it fails.

**Comment by robl45** [comment]
I believe you have a typo in one of the miner file names.  The Palginnvidia  neoscrypt is spelled Neocrypt

**Comment by UselessGuru** [comment]
> Is there a need to update to this? 

There is no update need right now, but all future changes will be based on this.
The only miner that has seen some important changes is ClaymoreDual.
You can also rename the existing Stats files. [Total Commander](www.totalcommander.com) has a good multi-rename tool.

> I believe you have a typo in one of the miner file names. The Palginnvidia neoscrypt is spelled Neocrypt

Thank you! [Fixed](https://github.com/UselessGuru/MultiPoolMiner/commit/3595a00480ccb4aecbea0e304820b1698bb2ef2b).

**Comment by evanvz** [comment]
Found this in CcminerSib.ps1

    "nist5"         = "" # fastest
    "_nist5"        = "" # my best values for 1080ti/1070/10603G " -i 26.75,26.25,24.75" # fastest

**Comment by evanvz** [comment]
Got this message when benchmarking ClaymoreNvidia

WARNING: NVIDIA miner 'ClaymoreNvidia_Blake2s60' (Ethash|Blake2s) [GPU Devices: All] failed - process handle is missing

Same happen with ClaymoreNvidia_Blake2s80 & ClaymoreNvidia_Blake2s40
