### ISSUE TITLE
Is there a way to make it less agressive with fails?

### ISSUE THREAD

**Issue by robl45** [UselessGuru/MultiPoolMiner#86]
Example, currently my system is saying tribus algorithm failed on Device 2 while that same miner and algorithm are rocking on Device 0 and 1.    I know the miner works, I'm not sure what happened that it says fail, but it would be nice if it would come back relatively quickly instead of just sitting out for awhile.

**Comment by UselessGuru** [comment]
> it would be nice if it would come back relatively quickly instead of just sitting out for awhile.

It will wait for $Interval. 

> tribus algorithm failed on Device 2 

Probably intensity too high. What happens when you run the same command stand-alone?

**Comment by robl45** [comment]
Can $interval be adjustmed and where is it?

It seems to work fine. i watch them going

**Comment by UselessGuru** [comment]
Setup.bat -> Advanced Settings -> Benchmark Interval

**Comment by robl45** [comment]
benchmark interval is 120 seconds.  These stay out much longer than 120 seconds.

**Comment by UselessGuru** [comment]
What do you mean with 'These stay out much longer' ?

**Comment by robl45** [comment]
So like I'll see on the screen that Tribus failed on whatever miner and its there for much longer than whatever the benchmark interval is.  It doesn't come back to the list of algorithms until well after 120 seconds.
