### ISSUE TITLE
DSTM Crashing

### ISSUE THREAD

**Issue by robl45** [UselessGuru/MultiPoolMiner#87]
DSTM was working fine, now it just crashes when loading the specific file for my machine. If I use the generic start bat in the bin folder it will run fine.  I don't know if there is some change at MPH causing it?

**Comment by UselessGuru** [comment]
> I don't know if there is some change at MPH causing it?

I doubt this.
Locate the command MPM UGE is using to launch DSTM. Try running the exact same parameter in DOS window.
If it crashes post screen output or screen shot here.

**Comment by robl45** [comment]
It seems to be working now, I believe it was something with the telemetry server being down as I saw in the forum.
