### ISSUE TITLE
Error on launch : no miner

### ISSUE THREAD

**Issue by BobTheTool** [UselessGuru/MultiPoolMiner#89]
Hi, 
your miner seems to be promising. The problem is when I set my setting and click apply this appear : 
![error](https://user-images.githubusercontent.com/36423775/36269478-95d6a294-1279-11e8-95e0-f982a6cfb1cb.jpg)

there is no miner in my folder,any is downloaded. I also encountered another problem, I cant open setup.bat. 
Please can you explane how to get rid of this error ? and how to start with your miner ?
Thanks man, you are doing great

**Comment by BobTheTool** [comment]
Any help ?

**Comment by evanvz** [comment]
Hi

It is normally an indication that you don't have any miner files in your BIN folder. It should start downloading the miner files to the DOWNLOAD folder and then extract them to your BIN folder.

Do you have any files in these folders!

Start maybe with just one algo and see.

Did you have these problems when you use the MPM main miner. If it work for you there, you can always copy that DOWNLOAD folder into this miner.

This miner uses a different ver of PowerShell.

And maybe start with a clean install.

Hope you manage.

E

**Comment by BobTheTool** [comment]
Hi, 
i have a version of multipoolminer which download correctly all miner.
In this version i start and no miner is dowbloaded at all. I don't have any bin folder in this version.
I have downloaded the last clon on uselessguru multipool page and have done multiple fresh instal of it, no solution.
I didn't have any download folder also.
I'm stuck right and really want to test this miner.
Thanks for your help

**Comment by evanvz** [comment]
Hi

When I came over from MPM to UselessGuru I noticed that the Powershell version aren't the same. 

Maybe start there:
Goto https://github.com/PowerShell/PowerShell/releases and select the version for our OS and make sure it installs correctly without errors.

On My Win10 rig (very small) I have PS 6.0.0-rc2 & PS 6.0.1-x64 installed. Runs without problems.

I just tried on my Win7 masjien with PS 6.0.0-rc2 installed and it keep trying to install PS. With PS6.0.1 x64 the same. No joy. Keep on trying to re-install PS 6.0.0-rc2 with errors.

This may be a Win7 dependensie problem.

Perhaps start by only enabling one coin to mine, say Ethash

Download from: https://github.com/ethereum-mining/ethminer/releases/download/v0.12.0/ethminer-0.12.0-Windows.zip

and extract to .\Bin\Ethash-Ethminer

The error messages I see looks more like a PowerShell version error perhaps.

I hope you manage as I like this version.

Cheers.
E

**Comment by BobTheTool** [comment]
Thanks for your precious advices !
I will try that :)
Can you give me all the miner folders name and path ? I will try to manually add every folder for every miner, the  download miners from github. (Because apparently miners path are not the same as the legacy MPM.

**Comment by evanvz** [comment]
Can you handle around 220Mb download Then I can Google Drive it or something The hole BIN folder

**Comment by BobTheTool** [comment]
Yes i can men and It would be very much appreciated, to have the whole bin folder and the lastest release of each miner :) I'm waiting your link !

**Comment by evanvz** [comment]
Hope this works for you. That's only the normal miners... not updated

Let me know.

https://drive.google.com/drive/folders/1G24wS-EsRAnZ-Ltm2qSrNGahx9W57N14?usp=sharing
