### ISSUE TITLE
MPM Setup window appears blank (white)

### ISSUE THREAD

**Issue by Coinminer24** [UselessGuru/MultiPoolMiner#9]
I am attempting to test this out (the features look great!); however, when I run setup the powershell window that opens is totally blank white. Unsure if it is related to an issue I am having where when Windows PowerShell ISE opens files up the window also appears totally blank.

**Comment by UselessGuru** [comment]
Very most likely: Yes!

This is one of the things I also struggle: Powershell Profiles.

**Comment by Coinminer24** [comment]
Any way I can setup without GUI? Just edit bat files directly?

I am really confused why it is happening. Until I did latest windows update I was able to edit PowerShell files no problem. Now the windows just appear blank white, which is presumably what causes the issue for MPM.

**Comment by UselessGuru** [comment]
> Any way I can setup without GUI? Just edit bat files directly?

Make sure you have the very latest code - I just made some impoertant changes. Then copy 'Config.sample.ps1' to 'Config.ps1', Then edit manually. Run 'Start.bat'.

**Comment by Coinminer24** [comment]
Thank you. Will give that a go. The PowerShell issue seems to be to do with Windows update to creators edition - will have to post on some Microsoft forums and see if can get that fixed

**Comment by Coinminer24** [comment]
At the moment it doesn't work because none of the miners are downloaded, I assume setup was meant to download them? Since I am not able to run this I don't have all the miners

**Comment by UselessGuru** [comment]
Yes - but if it does not download then there are other problems with your Powershell config.

Workaroud for you:
Get the miner download path from each miner file (variable '$URI').
Download the miners, Then extract the file to the path '$Path'.

**Comment by Coinminer24** [comment]
I haven’t had a chance to download miners yet manually but using nemosminer the downloads work on that. Do you call them in a different way? For my understanding should the downloads be done by the start.bat or only setup?

In parallel I am posting on some PS forums to see if I can figure out what the Fall Creators Update has down to the GUI part

**Comment by UselessGuru** [comment]
Any news? 

BTW I have uploaded a new version with many fixes. Please download the zip file and copy the contents over the old installation.

**Comment by Coinminer24** [comment]
Sorry been really busy, not had a change to test GUI. Recommendations on PowerShell forum are create new username etc. in Windows... Hopefully this weekend I will try the miner sans setup GUI. It appears the miners will download, but were just being slow.

**Comment by Coinminer24** [comment]
Testing it out on another machine and then will copy files over. Will keep you up to date on this other issue. Really like the setup GUI! However, it sometimes overwrites manual edits to other figures e.g. benchmark duration. A few of the miners aren't downloading for some reason, may have to get manually.
BTW, do you have any particular recommended set of algos? using X17, neoscrypt, lyra2RE2 at the moment

**Comment by UselessGuru** [comment]
> BTW, do you have any particular recommended set of algos? using X17, neoscrypt, lyra2RE2 at the 
moment

Refer to the ones included in Config.sample.ps1
