### ISSUE TITLE
Zergpool server address

### ISSUE THREAD

**Issue by robl45** [UselessGuru/MultiPoolMiner#90]
I believe the zergpool address is wrong in the pool file.  It should be mine.zergpool.com Port with no algorithm in the beginning.  Currently it just says zergpool.com.  I edited my file and its connecting and mining.

**Comment by evanvz** [comment]
Hi

Are you revering to mine.zergpool.com and/or zerg.zergpool.com (aka zergpool.com)

zergpool.com (198.251.81.136) FranTech Solutions
mine.zergpool.com (198.251.81.136) FranTech Solutions
zerg.zergpool.com (104.24.124.210) CloudFlare

These pages all looks the same unless someone has cloned it. Havn't looked inito ownership of these.

So if your balance stayed the same after change, you should be good. They mostlikely going over if not already to CloudFlare for DDos protection and so on.

The Forums should be a better place to ask this interessing question regarding the correct address to mine to.

My guess that is.

Cheers.
E

**Comment by robl45** [comment]
The correct address to mine is mine.zergpool.com with port.  No algorithm in front and only mine.zergpool.com.  I had to edit things to get it work properly.  I'm not completely sure if just zergpool.com will work, but my understanding is all will stop soon besides mine.zergpool.com

**Comment by evanvz** [comment]
Shot

Then maybe you should upload the file for UselessGuru to checkout and amend the current miner file in his build.

Not user where he is, as he's doesn't seem to be answering issues on his build. See he's doing a lot of update on MPM. Maybe thats why. As this is his own personal build he uses.

Cheers

**Comment by robl45** [comment]
I don't know enough about the code. I know what the miner address should be and what works for me, but I don't want to take the chance and screw things up for everyone else.  The one I did for blazepool worked but was missing algorithm, still worked, but I don't want other people losing money because of me.

**Comment by UselessGuru** [comment]
Zergpool file is available: https://github.com/UselessGuru/MultiPoolMiner/blob/master/Pools/Zergpool.ps1
