### ISSUE TITLE
Kicking pools and just using MPH

### ISSUE THREAD

**Issue by robl45** [UselessGuru/MultiPoolMiner#93]
I'm using MPH and Hashrefinery and Zergpool.  After awhile, happened twice tonight, it just starts using MPH. I think eventually it might go back, but it makes no sense that its kicking multiple pools at the same time.  Previously I ran zergpool and zpool together and sometimes it would say no pool available for a little bit but it would keep going.  Profitability is much lower when it just uses MPH.

**Comment by platinum4** [comment]
Change your runs to 600 or 900 seconds you may be making too many API calls to the pool and triggering a DDOS block

**Comment by robl45** [comment]
I tried as suggested although I moved to 120 seconds instead of 600 or 900 and same problem, its now just mining MPH instead of zergpool and hashrefinery.

**Comment by robl45** [comment]
Assuming its kicking the pools and I can't really see anything in the logs to verify that, is there a way to change watchdog to bring them back sooner?

**Comment by UselessGuru** [comment]
> no... disable watchdog.

**Comment by platinum4** [comment]
Hi,  Zergpool sucks and hashrefinery is not profitable because of fee BYE

**Comment by UselessGuru** [comment]
WD should be fixed in https://github.com/UselessGuru/MultiPoolMiner/archive/master.zip
