### ISSUE TITLE
Bminer still fails with watchdog off

### ISSUE THREAD

**Issue by platinum4** [UselessGuru/MultiPoolMiner#95]
Hi,

Fix this shit, watchdog false still fails

**Comment by platinum4** [comment]
Hurry the fuck up this fork has been neglected and this is an easy fix, this fork just keeps closing Bminer

**Comment by platinum4** [comment]
Hi

**Comment by UselessGuru** [comment]
@platinum4 

I don't quite like your tone :-)

**Comment by platinum4** [comment]
I paid good money for this fork buster!!!

**Comment by platinum4** [comment]
Hi,

If this is not fixed, you will get formal write-up and will go on permanent record!!!

BYE!

**Comment by UselessGuru** [comment]
> I paid good money for this fork buster!!!

Thank you for the $$$
