### ISSUE TITLE
No pools available on new 03.24.2018 fork

### ISSUE THREAD

**Issue by platinum4** [UselessGuru/MultiPoolMiner#96]
Hi,

What is this?

C:\MultiPoolMiner-master>setx GPU_FORCE_64BIT_PTR 1

SUCCESS: Specified value was saved.

C:\MultiPoolMiner-master>setx GPU_MAX_HEAP_SIZE 100

SUCCESS: Specified value was saved.

C:\MultiPoolMiner-master>setx GPU_USE_SYNC_OBJECTS 1

SUCCESS: Specified value was saved.

C:\MultiPoolMiner-master>setx GPU_MAX_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\MultiPoolMiner-master>setx GPU_SINGLE_ALLOC_PERCENT 100

SUCCESS: Specified value was saved.

C:\MultiPoolMiner-master>setx CUDA_DEVICE_ORDER PCI_BUS_ID

SUCCESS: Specified value was saved.

C:\MultiPoolMiner-master>set "command=& .\multipoolminer.ps1"

C:\MultiPoolMiner-master>if not exist "Config.ps1" set "command=& .\Setup.ps1"

C:\MultiPoolMiner-master>powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "& .\Setup.ps1"
Preparing setup...
Loading available pools - this may take up to 165 seconds...
No pools available.
At C:\MultiPoolMiner-master\Setup.ps1:36 char:5
+     Throw "No pools available. "
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No pools available. :String) [], RuntimeException
    + FullyQualifiedErrorId : No pools available.

**Comment by platinum4** [comment]
[Debug.zip](https://github.com/UselessGuru/MultiPoolMiner/files/1844954/Debug.zip)

**Comment by platinum4** [comment]
Doesn't work with old pool files either.

**Comment by platinum4** [comment]
2018-03-24 21:18:02 INFO: Applying configuration from Config.ps1...
Transcript started, output file is .\Logs\2018-03-24_21-18-03.txt
Copy-Item : An item with the specified name C:\MultiPoolMiner-master_032418_nightly\Debug\Pools already exists.
At C:\MultiPoolMiner-master_032418_nightly\MultiPoolMiner.ps1:82 char:5
+     Copy-Item "Pools" "Debug" -Recurse
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\MultiPoolMin...tly\Debug\Pools:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.CopyItemCommand

Copy-Item : An item with the specified name C:\MultiPoolMiner-master_032418_nightly\Debug\Miners already exists.
At C:\MultiPoolMiner-master_032418_nightly\MultiPoolMiner.ps1:83 char:5
+     Copy-Item "Miners" "Debug" -Recurse
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (C:\MultiPoolMin...ly\Debug\Miners:String) [Copy-Item], IOException
    + FullyQualifiedErrorId : DirectoryExist,Microsoft.PowerShell.Commands.CopyItemCommand

2018-03-24 21:18:04 INFO: Loading miner APIs...
2018-03-24 21:18:04 INFO: Updating exchange rates from Coinbase...
2018-03-24 21:18:05 INFO: Loading saved statistics...
2018-03-24 21:18:05 INFO: Loading pool information...
2018-03-24 21:18:05 WARNING: No pools available.

**Comment by platinum4** [comment]
It'd be awesome to try this but it doesn't load any pools.

**Comment by UselessGuru** [comment]
Try again.

DL [new Zip file](https://github.com/UselessGuru/MultiPoolMiner/archive/master.zip).

Fixed all this: https://github.com/UselessGuru/MultiPoolMiner/commit/68069a771cae6068ea3506e13aed18d814ddc737
