### ISSUE TITLE
Get-GPUdevices

### ISSUE THREAD

**Issue by evanvz** [UselessGuru/MultiPoolMiner#98]
Hi

Just tried your new master build and received this message.
[2018-04-05_17-27-16.txt](https://github.com/UselessGuru/MultiPoolMiner/files/1880678/2018-04-05_17-27-16.txt)

2018-04-05 17:27:16 INFO: Applying configuration from Config.ps1...
Transcript started, output file is .\Logs\2018-04-05_17-27-16.txt
Get-GPUdevices : The term 'Get-GPUdevices' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or
if a path was included, verify that the path is correct and try again.
At D:\Downloads\MPM\UselessGuru\MultiPoolMiner-master-5 April\MultiPoolMiner.ps1:75 char:10
+ $GPUs = (Get-GPUdevices $Type $DeviceSubTypes)
+          ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-GPUdevices:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by UselessGuru** [comment]
Fixed with latest changes.
https://github.com/UselessGuru/MultiPoolMiner/archive/master.zip
