### ISSUE TITLE
ExcavatorNividia

### ISSUE THREAD

**Issue by evanvz** [UselessGuru/MultiPoolMiner#99]
Hi

Getting this when benchmarking equihash

[warning] core | Command exec: onvalid stoi argument

**Comment by platinum4** [comment]
Excavators after 1.4.4 don't work on non-NH stratums

**Comment by evanvz** [comment]
Noted. Only using MPH Pool with small rig. Pool switching not good for small rig as payouts takes for ever.

Anyway. Cheers.

Thz
